name: Terraform CI/CD

on:
  push:
    paths:
      - 'envs/**'
      - 'modules/**'
      - 'terraform.tfstate.d/**'
      - 'provider.tf'

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init
      working-directory: ./envs/pre-prod
    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: ./envs/pre-prod
    - name: Terraform Apply
      run: terraform apply -var-file="terraform.tfvars"
      working-directory: ./envs/pre-prod
