name: Terraform CI/CD for prod

on:
  push:
    branches :
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-west-2
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init
      working-directory: ./envs/prod
    - name: Terraform Plan
      run: terraform plan -var-file="prod.tfvars"
      working-directory: ./envs/prod
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="prod.tfvars"
      working-directory: ./envs/prod
